# -*- coding: utf-8 -*-
"""Data Collection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L7Fzsd4oKQodzBhclcfc6hFDJKl8UcFL

# Data Collection
Permasalahan yang sering ditemui saat ingin mencari data adalah data tersebut berbentuk pdf dimana tidak jarang memaksa kita untuk input data secara manual. Hal ini tentu membutuhkan banyak waktu dan tenaga. Oleh karena itu akan di bagikan cara menconvert data dari pdf ke dalam format excel dan documents.

## Connect Gdrive kedalam Colab
Pada tutorial telah dijelaskan bagaimana step by step mengkoneksikan gdrive kedalam collab.
Apabila mengalami kesulitan pada tahap ini, mohon dibaca "PANDUAN MENGGUNAKAN GOOGLE COLABORATORY" secara seksama
"""

# Mengakses google drive ke dalam google colaboratory
from google.colab import drive
drive.mount('/content/gdrive')

"""## Import Packages/Library
Dalam turorial ini, anda akan diajarkan untuk convert data dengan library yang terdapat dalam python. 
- Tabula Documentation : https://tabula-py.readthedocs.io/en/latest/
- pdf2docx converter Documentation : https://dothinking.github.io/pdf2docx/quickstart.convert.html

Akan tetapi ke-2 library yang akan digunakan bukan merupakan bawaan notebook, oleh karena itu diperlukan install library secara independent. Berikut caranya
"""

# Install library tabula untuk convert pdf to excel (read tables in pdf into DataFrame)
!pip install tabula-py

# Install library pdf2docx untuk convert pdf to document
!pip install pdf2docx

# Import Packages/Library
import os
import tabula
from pdf2docx import Converter

# Inisiasi directory tempat data akan dibaca dan disimpan
path = "gdrive/MyDrive/Mini Course/Data Analytics/" #silahkan masukkan path sesuai dengan letak data di drive masing-masing

# Cek directory untuk memastikan data tersimpan di dalamnya
os.listdir(path)

"""## Convert Pdf to .xlsx and .csv format
Dalam mengconvert file pdf kedalam excel kita akan menggunakan module tabula. Ada beberapa argument yang ditambahkan untuk membantu mengatur spesifikasi output yang diharapkan.
"""

# Read PDf file
df = tabula.read_pdf(path + 'Provinsi Jawa Timur Dalam Angka 2020-pages-85.pdf', pages = 1, lattice = True, multiple_tables=True)[0]

# Menampilkan 5 data teratas dari file
df.head()

"""Perhatikan table diatas, dalam penamaan nama kolom, formatnya masih kurang rapi, selain itu ada kolom-kolom yang masuk ke dalam baris."""

# Cleaning data
df_clean = df.iloc[3:].reset_index(drop=True) #mengambil data dari baris index ke-3, dan mereset index agar mulai dari 0

df_clean.columns = [df.columns[0],df['2018'][0],df['Unnamed: 0'][0]] #rename nama kolom

# Menampilkan 5 data teratas dari file
df_clean.head()

# Cleaning data columns
df_clean.columns = df_clean.columns.str.replace('\r', '/') # Mengganti "\r" menjadi spasi
df_clean

#Cleaning Data Content
df_clean = df_clean.drop(labels=29, axis=0) #hapus baris index ke-29
df_clean['Pendapatan/Revenues'] = df_clean['Pendapatan/Revenues'].str.replace(" ", "").str.replace(",", ".") #hapus spasi dan ubah tanda koma menjadi titik
df_clean['Belanja/Expenditures'] = df_clean['Belanja/Expenditures'].str.replace(" ", "").str.replace(",", ".") #hapus spasi dan ubah tanda koma menjadi titik

#Cek Tipe Data
df_clean.info()

df_clean['Pendapatan/Revenues'] = df_clean['Pendapatan/Revenues'].astype(float)
df_clean['Belanja/Expenditures'] = df_clean['Belanja/Expenditures'].astype(float)

df_clean.head()

"""Sekarang anda telah mendapatkan kolom dengan pattern yang mudah dibaca. Berikut akan di contohkan cara menyimpan data kedalam format .xlsx dan .csv."""

#convert DataFrame to .xlsx
df_clean.to_excel(path + 'convert_excel.xlsx', index=None) # tidak mengimpan index dari dataframe tersebut

#convert DataFrame to .csv
df_clean.to_csv(path + 'convert_csv.csv', index=None) # tidak mengimpan index dari dataframe tersebut

"""Anda telah berhasil mengcovert pdf kedalam format .xlsx dan .csv. Selanjutnya anda dapat melihat data pada drive anda.

## Convert Pdf to Docx
Dalam mengconvert file pdf kedalam document file kita akan menggunakan module pdf2docx. Untuk lebih jelasnya perhatikan code dibawah ini.
"""

# Pilih directory tempat file pdf tersimpan
pdf_file = path + 'Provinsi Jawa Timur Dalam Angka 2020-pages-85.pdf'

# Pilih directory tempat data docx akan tersimpan, dan masukkan nama file untuk file document
docx_file = path + 'Provinsi Jawa Timur Dalam Angka 2020-pages-85.docx' # nama file bisa diganti

# Convert pdf to docx
cv = Converter(pdf_file)

# Proses pdf dan pilih halaman yang akan di convert
cv.convert(docx_file, start=0, end=None) #convert pdf halaman pertama
cv.close()

"""Anda telah berhasil mengconvert pdf kedalam 2 format file yang berbeda. Untuk memastikan data sudah tersimpan, cek kembali data dalam directory anda.
> *membutuhkan sedikit waktu untuk save data ke dalam drive*
"""

os.listdir(path)

